name: PR Smoke Tests

on:
  pull_request:
    branches: [ "**" ]

jobs:
  unit:
    name: Unit checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

  smoke:
    name: Smoke API tests
    runs-on: ubuntu-latest
    needs: unit
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
      REQRES_BASE_URL: ${{ secrets.REQRES_BASE_URL }}
      X_API_KEY: ${{ secrets.X_API_KEY }}
      API_RETRY_MAX: ${{ vars.API_RETRY_MAX }}
      API_RETRY_BASE_MS: ${{ vars.API_RETRY_BASE_MS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Export BASE_URL if provided
        if: ${{ env.BASE_URL != '' }}
        run: echo "BASE_URL=${{ env.BASE_URL }}" >> $GITHUB_ENV

      - name: Run smoke tests
        run: npx playwright test -g "smoke"

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-html-report
          path: reports/html
          if-no-files-found: ignore

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-results
          path: test-results
          if-no-files-found: ignore


